### PR TITLE
Secrets in container definition 

### LINKED ISSUE #76: Secrets in Container Definitions
This is a similar question to this: #63, however with some differences.

1. I see that aws now has support for specifying a secrets object in the container definitions: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

The questions I have are:

1. is it possible to create custom helpers that can actually take a secrets environment variable and inject it into the container definitions, similar to the `full_image_name` and `env_vars` helpers. So I would do something like the below in base.rb or another variables file:
```ruby
@secrets = helper.secrets(%Q[
    DB_PASSWORD=/my_app/db_password
    APP_KEY=/my_app/app_key
])
```
which would convert it to something like this:
```json
[{
    "name": "DB_PASSWORD",
    "valueFrom": "/my_app/db_password"
},
{
    "name": "APP_KEY",
    "valueFrom": "/my_app/app_key"
}]
```
Which i would then add to the container definitions in `main.json.erb` like below:

```ruby
<% if @secrets %>
      "secrets": <%= @secrets.to_json %>,
<% end %>
```

This would allow me to inject secrets into my containers using aws cloudformation's new way of injecting secrets.

2. Is it possible to interpolate environment variables into our variable declaration, for instance in the example above:
```ruby
@secrets = helper.secrets(%Q[
    DB_PASSWORD=/my_app/db_password
    APP_KEY=/my_app/app_key
])
```
changing that to be:
```ruby
@secrets = helper.secrets(%Q[
    DB_PASSWORD=/my_app-{environment}/db_password
    APP_KEY=/my_app-{environment}/app_key
])
```

### PR DESCRIPTION
**Pull request by alexbeattie42**
TODO: Update documentation when implementation is approved
* Update template files to insert secrets
* Create helper method for secrets and secrets_file
* Add `--secrets_path` to specify aws ssm parameter path (ex. --secrets_path=/{environment}/path/to/parameter/ )
* Will substitute {environment} in the path to the current UFO_ENV
* Tested task-definition generation on my work project using Fargate

Resolves #76

### CODE REVIEW

**Comment by alexbeattie42** [comment]
What is required to move this forward? Is my implementation sufficient (should I update the docs accordingly?) @tongueroo

**Comment by tongueroo** [comment]
So tested this a bit ago. And it seems to not be working. Didn’t have time to put together more details but figure will follow up. Think main issue is the implementation appears not to be working yet. Bummer. 😔

**Comment by alexbeattie42** [comment]
What part of it isn't working? Is it failing to build task definitions or is it failing in fargate? When I tested for my project it built the task definitions successfully and deployed to my fargate cluster.

**Comment by tongueroo** [comment]
Here's an error when running `ufo ship` using the demo repo from the quickstart.

    $ ufo ship
    ...
    Docker push took 0s.
    Building Task Definitions...
    Generating Task Definitions:
    Traceback (most recent call last):
            26: from /home/ec2-user/tongueroo/ufo/exe/ufo:14:in `<main>'
            25: from /home/ec2-user/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
            24: from /home/ec2-user/tongueroo/ufo/lib/ufo/command.rb:43:in `dispatch'
            23: from /home/ec2-user/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
            22: from /home/ec2-user/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
            21: from /home/ec2-user/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
            20: from /home/ec2-user/tongueroo/ufo/lib/ufo/cli.rb:69:in `ship'
            19: from /home/ec2-user/tongueroo/ufo/lib/ufo/tasks/builder.rb:8:in `ship'
            18: from /home/ec2-user/tongueroo/ufo/lib/ufo/tasks/builder.rb:14:in `build'
            17: from /home/ec2-user/tongueroo/ufo/lib/ufo/tasks/builder.rb:25:in `build'
            16: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl.rb:14:in `run'
            15: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl.rb:63:in `build_task_definitions'
            14: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl.rb:63:in `each'
            13: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl.rb:64:in `block in build_task_definitions'
            12: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/task_definition.rb:25:in `build'
            11: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/task_definition.rb:58:in `copy_instance_variables'
            10: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/task_definition.rb:21:in `template_scope'
             9: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/task_definition.rb:21:in `new'
             8: from /home/ec2-user/tongueroo/ufo/lib/ufo/template_scope.rb:11:in `initialize'
             7: from /home/ec2-user/tongueroo/ufo/lib/ufo/template_scope.rb:37:in `load_variables_file'
             6: from /home/ec2-user/tongueroo/ufo/lib/ufo/template_scope.rb:37:in `instance_eval'
             5: from ./.ufo/variables/base.rb:5:in `load_variables_file'
             4: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/helper.rb:94:in `secrets_file'
             3: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/helper.rb:46:in `secrets'
             2: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/helper.rb:46:in `map'
             1: from /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/helper.rb:48:in `block in secrets'
    /home/ec2-user/tongueroo/ufo/lib/ufo/dsl/helper.rb:48:in `gsub!': no implicit conversion of nil into String (TypeError)
    $ cat .env.secrets 
    # fine to have comment in this file
    $ 

Could be testing it incorrectly. Though took a quick look at the code and don't see how it could work. Unsure. Will take a closer look unless you get to it first. No sweat either way.

**Comment by alexbeattie42** [comment]
I found the issue was I was trying to access ENV['UFO_ENV'] directly which only works if you're setting the UFO_ENV with the command (what I'm doing with my project.  I changed it to use `Ufo.env` and tested it with the demo project and it should work now.

**Comment by tongueroo** [comment]
Handled by #106 instead

**Pull request closed without merging**
